       %macro push 2
                 push %1
                 push %2
       %endmacro

       %macro push 3
                 push %1
                 push %2
                 push %3
       %endmacro

       %macro push 4
                 push %1
                 push %2
                 push %3
                 push %4
       %endmacro

       %macro push 5
                 push %1
                 push %2
                 push %3
                 push %4
                 push %5
       %endmacro

       %macro push 6
                 push %1
                 push %2
                 push %3
                 push %4
                 push %5
                 push %6
       %endmacro

       %macro push 7
                 push %1
                 push %2
                 push %3
                 push %4
                 push %5
                 push %6
                 push %7
       %endmacro

       %macro push 8
                 push %1
                 push %2
                 push %3
                 push %4
                 push %5
                 push %6
                 push %8
       %endmacro

       %macro pop 2
                 pop %1
                 pop %2
       %endmacro

       %macro pop 3
                 pop %1
                 pop %2
                 pop %3
       %endmacro

       %macro pop 4
                 pop %1
                 pop %2
                 pop %3
                 pop %4
       %endmacro

       %macro pop 5
                 pop %1
                 pop %2
                 pop %3
                 pop %4
                 pop %5
       %endmacro

       %macro pop 6
                 pop %1
                 pop %2
                 pop %3
                 pop %4
                 pop %5
                 pop %6
       %endmacro

       %macro pop 7
                 pop %1
                 pop %2
                 pop %3
                 pop %4
                 pop %5
                 pop %6
                 pop %7
       %endmacro

       %macro pop 8
                 pop %1
                 pop %2
                 pop %3
                 pop %4
                 pop %5
                 pop %6
                 pop %7
                 pop %8
       %endmacro
